name: Deploy to EKS

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # Authenticate to AWS via OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::354935533189:role/eks-github-actions-cluster-role
        aws-region: us-east-2

    # Build and push to ECR
    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push image
      env:
        ECR_REGISTRY: 354935533189.dkr.ecr.us-east-1.amazonaws.com
        IMAGE_NAME: flask-app
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        docker build -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Update kubeconfig for EKS
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name Kubernetes-demo--region us-east-2

    # Deploy using kubectl or Helm
    - name: Deploy to EKS
      run: |
        kubectl set image deployment/flask-app flask-app=354935533189.dkr.ecr.us-east-2.amazonaws.com/flask-app:${IMAGE_TAG}
        kubectl rollout status deployment/flask-app
